//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BKS_Books
    {
        public int BookID { get; set; }
        public string BookTitle { get; set; }
        public string ViewBookTitle { get; set; }
        public short VolNumber { get; set; }
        public string InternalID { get; set; }
        public int CMS_DialogLangID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int PageNumber { get; set; }
        public bool Free { get; set; }
        public byte[] FullText { get; set; }
        public int PublisherID { get; set; }
        public int SizeID { get; set; }
        public string PublishPlace { get; set; }
        public string PublishYear { get; set; }
        public int NewBoxViewCount { get; set; }
        public Nullable<bool> HasImageBook { get; set; }
        public Nullable<bool> HasImageCover { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string SearchBookTitle { get; set; }
        public Nullable<bool> HasTextBook { get; set; }
        public Nullable<bool> HasPdf { get; set; }
        public string ImageID { get; set; }
        public string Congress { get; set; }
        public string BookWeigh { get; set; }
        public string ISBN10 { get; set; }
        public string ISBN13 { get; set; }
        public string KeyWords { get; set; }
        public string PrintNumber { get; set; }
        public string Subject { get; set; }
        public Nullable<int> DataVersion { get; set; }
        public Nullable<bool> ShowText { get; set; }
        public string ShowTextUrl { get; set; }
    }
}
